[{"name": "test.test_hello_world.HelloWorld.test_first", "status": "failed", "message": "Function main was not found in file src.hello_world.", "passed": false, "points": ["p01-01.1"], "backtrace": ["  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python312\\Lib\\unittest\\case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\Tec\\Downloads\\Opgaver_dag1\\Opgaver_dag1\\e01_hello_world\\test\\test_hello_world.py\", line 18, in test_first\n    main()\n", "  File \"C:\\Users\\Tec\\Downloads\\Opgaver_dag1\\Opgaver_dag1\\e01_hello_world\\tmc\\utils.py\", line 80, in fail\n    raise AssertionError(err)\n"]}]